# Generated by Django 5.2.7 on 2025-10-13 01:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_equipmentdata'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('farm_name', models.CharField(blank=True, max_length=100, null=True)),
                ('farm_location', models.CharField(max_length=200)),
                ('farm_size', models.CharField(choices=[('small', 'Small (< 5 acres)'), ('medium', 'Medium (5–20 acres)'), ('large', 'Large (> 20 acres)')], max_length=20)),
                ('crop_type', models.CharField(max_length=50)),
                ('notifications', models.BooleanField(default=True)),
                ('language', models.CharField(default='English', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
