# Generated by Django 5.2.7 on 2025-10-13 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_chatlog_options_alter_equipmentdata_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensorreading',
            old_name='soil',
            new_name='soil_moisture',
        ),
        migrations.RenameField(
            model_name='sensorreading',
            old_name='created_at',
            new_name='timestamp',
        ),
        migrations.RemoveField(
            model_name='sensorreading',
            name='user',
        ),
        migrations.AddField(
            model_name='sensorreading',
            name='ph_value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
