# Generated by Django 5.2.7 on 2025-10-14 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_sensorreading_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensorreading',
            name='humidity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sensorreading',
            name='soil_moisture',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sensorreading',
            name='temperature',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
